"""empty message

Revision ID: 70168ddb2a98
Revises: 23bd6bdb4618
Create Date: 2017-11-22 17:58:03.005124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70168ddb2a98'
down_revision = '23bd6bdb4618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name2')
    # ### end Alembic commands ###
